spring.application.name=budget-service
server.port=8081

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/budgeting}

jwt.secret=${JWT_SECRET:r9Ny+vSPeELE77uGBaHt4ZTiNXCYprsRshmkPF9Y8GY=}
